### ISSUE TITLE
Can you please share one example to using the script in an automation or script [QUESTION] 

### ISSUE THREAD

**Issue by tomerbs** [pmazz/ps_hassio_entities#1]
**What is your question**
Can you please share one example of using the script in an automation or script.

**YAML configuration**
```yaml
# paste your configuration here
`'1596141541557':
  alias: '###New Script Off'
  sequence:
  - data:
      action: set_state_attributes
      entity_id: binary_sensor.neo_coolcam_door_sensor
      state: 'off'
    service: python_script.hass_entities``

**Screenshots**
If applicable, add your screenshots here.

**Version**
What is the version of the script?
I'm using version 1.1.0

**Additional information**
I was able to get it to work from lovelace but from an automation and script It's not working for meץ

**Comment by pmazz** [comment]
Your code is missing the `attributes:` array.
Invoking the `set_state_attributes` action requires to provide both `state` and `attributes`.

So your code should be:
``` yaml
'1596141541557':
  alias: '###New Script Off'
  sequence:
  - data:
      action: set_state_attributes
      entity_id: binary_sensor.neo_coolcam_door_sensor
      state: 'off'
      attributes:
        - attribute1: 'attribute value'
        - attribute2: 'attribute value'
    service: python_script.hass_entities
```
Check here for details:
<https://github.com/pmazz/ps_hassio_entities#set-both-state-and-attributes>

Or, in case you need to set the state only, your should use `action: set_state`.
Then your code should be:
``` yaml
'1596141541557':
  alias: '###New Script Off'
  sequence:
  - data:
      action: set_state
      entity_id: binary_sensor.neo_coolcam_door_sensor
      state: 'off'
    service: python_script.hass_entities
```
Check here for this case:
<https://github.com/pmazz/ps_hassio_entities#set-state-only>

Let me know if that helps.
