### ISSUE TITLE
[QUESTION] how do you change Just the Attribute  and Leave State The Current State

### ISSUE THREAD

**Issue by comet424** [pmazz/ps_hassio_entities#14]
**What is your question**
i want to be able just to change a attribute of the sensor.. but you need to add state.. i dont wanna change the state.. i just wanna be able to change the Attritube

**YAML configuration**
```yaml
# paste your configuration here
action: python_script.hass_entities
metadata: {}
data:
  action: set_state_attributes
  entity_id: climate.moms_furnace
  state: 
  attributes:
    - current_temperature: null
```

    - 
**Screenshots**
If applicable, add your screenshots here.

**Version**
What is the version of the script?

**Additional information**
Add any other relevant additional information here.
it works if i state : off   or heat   but i only wanna adjust the attritubue  not change the state
