### ISSUE TITLE
the script doesn't seem to run properly not catching the parameter "action" 

### ISSUE THREAD

**Issue by KonTiki1957** [pmazz/ps_hassio_entities#2]
I'm interested in using this script but I'm not succeeding, I always get the following error: [homeassistant.components.python_script.hass_entities.py] **Required parameter 'action' is missing.** with following HA script configuration. Can you give me a hint? Thank you.

**YAML configuration**
```yaml
prova_python_script:
  alias: prova python script
  sequence:
  - service: python_script.hass_entities
    data:
      service_data:
        action: set_state
        entity_id: sensor.temperatura_piano_sopra
        state: 30
        log_enabled: true
  mode: single
```

**Screenshots**
If applicable, add your screenshots here.

**Version**
latest
**Additional information**
Add any other relevant additional information here.

**Comment by pmazz** [comment]
I'm afraid your code is not correct.
There's no need of the ``service_data``  level.
Just put ``action``, ``entity_id`` and ``state`` below ``data:``.

This should work:
``` yaml
prova_python_script:
  alias: prova python script
  sequence:
  - service: python_script.hass_entities
    data:
      action: set_state
      entity_id: sensor.temperatura_piano_sopra
      state: 30
      log_enabled: true
  mode: single
```
Let me know if that helps.
