### ISSUE TITLE
Can I change the "name" attribute of a timer?

### ISSUE THREAD

**Issue by viktak** [pmazz/ps_hassio_entities#3]
**What is your question**
I have successfully used your script to change states/attributes of items in my config. However, when I try to change the `name` attribute of a timer, it simply doesn't happen.

**YAML configuration**
```yaml
# This is my automation:
  - service: python_script.hass_entities
    data:
      action: set_attributes
      entity_id: timer.boiler_viktors_office
      attributes:
        - name: "Currently"
# This is my lovelace item:
      - entity: timer.boiler_viktors_office
        name: Time remaining
        tap_action: none

# This is my timer:
boiler_viktors_office:


```

**Screenshots**
If applicable, add your screenshots here.

**Version**
What is the version of the script?
v1.1.0

**Additional information**
In the logs I didn't find anything obvious...
