### ISSUE TITLE
New attribute disappears on binary_sensor after state change

### ISSUE THREAD

**Issue by wilfredsmit** [pmazz/ps_hassio_entities#7]
**What is your question**
When I create a attribute on a binary_sensor that triggers the creation of the attribute, the attribute disappears after another state change of the binary sensor.

Is this by design? I would like the attribute to be permanent.

**YAML configuration**
```
---
alias: Oprit Hue
id: oprit_hue

trigger:
  - platform: state
    entity_id: binary_sensor.hue_reserve_motion_lumi
    from: "off"
    to: "on"

action:
  - service: python_script.hass_entities
    data:
      action: set_attributes
      entity_id: binary_sensor.hue_reserve_motion_lumi
      attributes: 
        - start: "{{ as_timestamp(now()) |float(0) }}"
```

**Screenshots**
Animated gif!
![Screen Recording (Systeemvoorkeuren)](https://user-images.githubusercontent.com/31591364/166255362-345c42a2-aa6e-41c9-be43-4b9dbf4367c2.gif)

**Version**
v1.1.0

**Additional information**
Logfile info:

2022-05-04 10:44:50 INFO (SyncWorker_2) [homeassistant.components.python_script] Executing hass_entities.py: {'log_enabled': True, 'action': 'set_attributes', 'entity_id': 'binary_sensor.hue_reserve_motion_lumi', 'attributes': [{'start': 1651653890.053345}]}
2022-05-04 10:44:50 DEBUG (SyncWorker_2) [homeassistant.components.python_script.hass_entities.py] Python Script: hass_entities.py -> START of action: set_attributes
2022-05-04 10:44:50 DEBUG (SyncWorker_2) [homeassistant.components.python_script.hass_entities.py]   Entity: 'binary_sensor.hue_reserve_motion_lumi' -> New attribute 'start': '1651653890.053345'
2022-05-04 10:44:50 DEBUG (SyncWorker_2) [homeassistant.components.python_script.hass_entities.py]   DONE -> Attributes set for entity 'binary_sensor.hue_reserve_motion_lumi'
2022-05-04 10:44:50 DEBUG (SyncWorker_2) [homeassistant.components.python_script.hass_entities.py] Python Script: hass_entities.py -> END of action: set_attributes
