### ISSUE TITLE
An unhandled error has occurred.  'NoneType' object is not callable

### ISSUE THREAD

**Issue by pos-ei-don** [pmazz/ps_hassio_entities#8]
Trying to set the friendly name at an **input_select** does nor work.

Using:

```
service: python_script.hass_entities
data:      
  action: set_attributes
  entity_id: input_select.home
  attributes:
    friendly_name: "abcd"
```

throws 

```
hass_entities error
An unhandled error has occurred.

'NoneType' object is not callable
```

dooing is directly in HASS works, but i need it in an automation!

**Comment by pmazz** [comment]
Your `attributes` section looks not well-formatted.

Try this:
```yaml
service: python_script.hass_entities
data:      
  action: set_attributes
  entity_id: input_select.home
  attributes:
    - friendly_name: "abcd"
```
